#ifndef PACKET_IDS_HPP
#define PACKET_IDS_HPP

#define PACKET_SOCKET_DISCONNECT_ID -2
#define PACKET_SOCKET_CONNECT_ID -1
#define PACKET_MESSAGE_ID 0
#define PACKET_LOGIN_ID 1
#define PACKET_MUHLE_FIELD_ID 2
#define PACKET_GAME_REQUEST_ID 3
#define PACKET_GAME_CODE_ID 4
#define PACKET_ABORT_GAME_ID 5
#define PACKET_GAME_PLACE 6
#endif