#ifndef PACKET_IDS_HPP
#define PACKET_IDS_HPP

#define PACKET_SOCKET_DISCONNECT_ID -2
#define PACKET_SOCKET_CONNECT_ID -1
#define PACKET_MESSAGE_ID 0
#define PACKET_LOGIN_ID 1
#define PACKET_MUHLE_FIELD_ID 2
#define PACKET_GAME_REQUEST_ID 3
#define PACKET_GAME_CODE_ID 4
#define PACKET_ABORT_GAME_ID 5
#define PACKET_GAME_PLACE_ID 6
#define PACKET_GAME_ATTACK_ID 7
#define PACKET_GAME_MOVE_ID 8
#define PACKET_GAME_JUMP_ID 9
#define PACKET_GAME_ENDED_ID 10

#endif