name: Makefile CI

on: 
  pull_request:
    branches: [ main ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install boost
       run: sudo apt-get update && sudo apt-get install libboost-all-dev 
    - name: make
      run: make
  # build-on-macOS:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: build2
  #     run: make
