name: Makefile CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install boost
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install libboost-dev-all
    - name: build
      run: make